"""
Seed script — run once to populate the database with Toronto-area care locations
and simulated live status data.

Usage:
    python seed.py           # seed if DB is empty
    python seed.py --reset   # wipe locations and reseed with full list
"""
import random
import sys
from datetime import datetime, timezone
from database import engine, SessionLocal, Base
import models  # noqa: F401 — registers all models with Base

Base.metadata.create_all(bind=engine)

CARE_LOCATIONS = [
    # ── Hospitals / ERs ──────────────────────────────────────────────────────
    {
        "name": "Toronto General Hospital",
        "type": "hospital",
        "address": "200 Elizabeth St",
        "city": "Toronto",
        "latitude": 43.6594,
        "longitude": -79.3883,
        "phone": "416-340-4800",
        "is_open_24_7": True,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["cardiac", "trauma", "general", "respiratory"],
    },
    {
        "name": "St. Michael's Hospital ER",
        "type": "er",
        "address": "36 Queen St E",
        "city": "Toronto",
        "latitude": 43.6534,
        "longitude": -79.3762,
        "phone": "416-360-4000",
        "is_open_24_7": True,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["trauma", "general", "cardiac"],
    },
    {
        "name": "Sunnybrook Health Sciences Centre",
        "type": "hospital",
        "address": "2075 Bayview Ave",
        "city": "Toronto",
        "latitude": 43.7232,
        "longitude": -79.3765,
        "phone": "416-480-6100",
        "is_open_24_7": True,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["trauma", "cardiac", "orthopedic", "general"],
    },
    {
        "name": "SickKids Hospital",
        "type": "hospital",
        "address": "555 University Ave",
        "city": "Toronto",
        "latitude": 43.6574,
        "longitude": -79.3902,
        "phone": "416-813-1500",
        "is_open_24_7": True,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["pediatric", "general"],
    },
    {
        "name": "Mount Sinai Hospital",
        "type": "hospital",
        "address": "600 University Ave",
        "city": "Toronto",
        "latitude": 43.6573,
        "longitude": -79.3906,
        "phone": "416-596-4200",
        "is_open_24_7": True,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["general", "respiratory", "cardiac"],
    },
    {
        "name": "North York General Hospital",
        "type": "hospital",
        "address": "4001 Leslie St",
        "city": "North York",
        "latitude": 43.7614,
        "longitude": -79.3437,
        "phone": "416-756-6000",
        "is_open_24_7": True,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["general", "trauma", "orthopedic"],
    },
    {
        "name": "Humber River Hospital",
        "type": "hospital",
        "address": "1235 Wilson Ave",
        "city": "North York",
        "latitude": 43.7433,
        "longitude": -79.5021,
        "phone": "416-242-1000",
        "is_open_24_7": True,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["general", "cardiac"],
    },
    {
        "name": "Scarborough Health Network — General",
        "type": "hospital",
        "address": "3050 Lawrence Ave E",
        "city": "Scarborough",
        "latitude": 43.7552,
        "longitude": -79.2411,
        "phone": "416-431-8200",
        "is_open_24_7": True,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["general", "trauma", "respiratory"],
    },
    # ── Urgent Care ───────────────────────────────────────────────────────────
    {
        "name": "Appletree Medical Group — King West",
        "type": "urgent_care",
        "address": "680 King St W",
        "city": "Toronto",
        "latitude": 43.6446,
        "longitude": -79.4023,
        "phone": "416-593-2273",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "20:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    {
        "name": "Medpoint Health Centres — Yonge & Eg",
        "type": "urgent_care",
        "address": "2300 Yonge St",
        "city": "Toronto",
        "latitude": 43.7053,
        "longitude": -79.3979,
        "phone": "416-932-9000",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "22:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general", "respiratory"],
    },
    {
        "name": "Bay-College Medical Centre",
        "type": "urgent_care",
        "address": "777 Bay St",
        "city": "Toronto",
        "latitude": 43.6591,
        "longitude": -79.3842,
        "phone": "416-977-7653",
        "is_open_24_7": False,
        "opening_time": "09:00",
        "closing_time": "21:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general", "mental_health"],
    },
    # ── Walk-in Clinics ───────────────────────────────────────────────────────
    {
        "name": "Women's College Hospital Walk-in",
        "type": "clinic",
        "address": "76 Grenville St",
        "city": "Toronto",
        "latitude": 43.6640,
        "longitude": -79.3880,
        "phone": "416-323-6400",
        "is_open_24_7": False,
        "opening_time": "08:30",
        "closing_time": "17:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    {
        "name": "Rexdale Community Health Centre",
        "type": "clinic",
        "address": "8 Taber Rd",
        "city": "Etobicoke",
        "latitude": 43.7306,
        "longitude": -79.5744,
        "phone": "416-744-0066",
        "is_open_24_7": False,
        "opening_time": "09:00",
        "closing_time": "17:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general", "mental_health"],
    },
    # ── Pharmacies ────────────────────────────────────────────────────────────
    {
        "name": "Shoppers Drug Mart — Yonge & Dundas",
        "type": "pharmacy",
        "address": "700 Yonge St",
        "city": "Toronto",
        "latitude": 43.6672,
        "longitude": -79.3860,
        "phone": "416-961-0707",
        "is_open_24_7": True,
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    {
        "name": "Rexall Pharmacy — Bay St",
        "type": "pharmacy",
        "address": "100 Bay St",
        "city": "Toronto",
        "latitude": 43.6489,
        "longitude": -79.3800,
        "phone": "416-368-4400",
        "is_open_24_7": False,
        "opening_time": "07:00",
        "closing_time": "23:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    # ── More Hospitals / ERs (GTA) ───────────────────────────────────────────
    {
        "name": "Michael Garron Hospital",
        "type": "hospital",
        "address": "825 Coxwell Ave",
        "city": "Toronto",
        "latitude": 43.6892,
        "longitude": -79.3134,
        "phone": "416-469-6000",
        "is_open_24_7": True,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["general", "respiratory", "cardiac"],
    },
    {
        "name": "Credit Valley Hospital",
        "type": "hospital",
        "address": "2200 Eglinton Ave W",
        "city": "Mississauga",
        "latitude": 43.5621,
        "longitude": -79.6762,
        "phone": "905-813-2200",
        "is_open_24_7": True,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["general", "trauma", "pediatric"],
    },
    {
        "name": "Trillium Health Partners — Mississauga",
        "type": "hospital",
        "address": "100 Queensway W",
        "city": "Mississauga",
        "latitude": 43.5892,
        "longitude": -79.6431,
        "phone": "905-848-7100",
        "is_open_24_7": True,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["general", "cardiac", "trauma"],
    },
    {
        "name": "William Osler Health — Brampton Civic",
        "type": "hospital",
        "address": "2100 Bovaird Dr E",
        "city": "Brampton",
        "latitude": 43.7312,
        "longitude": -79.7621,
        "phone": "905-494-2120",
        "is_open_24_7": True,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["general", "trauma", "pediatric"],
    },
    {
        "name": "Rouge Valley Health — Centenary",
        "type": "hospital",
        "address": "2867 Ellesmere Rd",
        "city": "Scarborough",
        "latitude": 43.7734,
        "longitude": -79.2134,
        "phone": "416-284-8131",
        "is_open_24_7": True,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["general", "respiratory"],
    },
    {
        "name": "Mackenzie Health — Richmond Hill",
        "type": "hospital",
        "address": "10 Trench St",
        "city": "Richmond Hill",
        "latitude": 43.8821,
        "longitude": -79.4421,
        "phone": "905-883-1212",
        "is_open_24_7": True,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["general", "cardiac", "orthopedic"],
    },
    {
        "name": "Markham Stouffville Hospital",
        "type": "hospital",
        "address": "381 Church St",
        "city": "Markham",
        "latitude": 43.8765,
        "longitude": -79.2612,
        "phone": "905-472-7000",
        "is_open_24_7": True,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["general", "pediatric", "trauma"],
    },
    {
        "name": "Oakville Trafalgar Memorial Hospital",
        "type": "hospital",
        "address": "327 Reynolds St",
        "city": "Oakville",
        "latitude": 43.4521,
        "longitude": -79.6912,
        "phone": "905-845-2571",
        "is_open_24_7": True,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["general", "cardiac", "respiratory"],
    },
    # ── More Urgent Care / Walk-in ────────────────────────────────────────────
    {
        "name": "Appletree Medical — Queen West",
        "type": "urgent_care",
        "address": "798 Queen St W",
        "city": "Toronto",
        "latitude": 43.6451,
        "longitude": -79.4123,
        "phone": "416-703-6666",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "20:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    {
        "name": "Toronto Western Hospital Urgent Care",
        "type": "urgent_care",
        "address": "399 Bathurst St",
        "city": "Toronto",
        "latitude": 43.6542,
        "longitude": -79.4021,
        "phone": "416-603-2580",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "22:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general", "orthopedic"],
    },
    {
        "name": "Medpoint — Bloor & Bathurst",
        "type": "urgent_care",
        "address": "701 Bloor St W",
        "city": "Toronto",
        "latitude": 43.6642,
        "longitude": -79.4182,
        "phone": "416-532-9000",
        "is_open_24_7": False,
        "opening_time": "09:00",
        "closing_time": "21:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general", "respiratory"],
    },
    {
        "name": "Sheridan Walk-in Clinic",
        "type": "urgent_care",
        "address": "2225 Sheppard Ave E",
        "city": "North York",
        "latitude": 43.7721,
        "longitude": -79.3821,
        "phone": "416-491-5555",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "20:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general", "pediatric"],
    },
    {
        "name": "Mississauga Urgent Care — Hurontario",
        "type": "urgent_care",
        "address": "3180 Hurontario St",
        "city": "Mississauga",
        "latitude": 43.5812,
        "longitude": -79.6421,
        "phone": "905-276-8888",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "22:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    # ── More Clinics ──────────────────────────────────────────────────────────
    {
        "name": "Crossways Clinic",
        "type": "clinic",
        "address": "2340 Dundas St W",
        "city": "Toronto",
        "latitude": 43.6621,
        "longitude": -79.4521,
        "phone": "416-604-9898",
        "is_open_24_7": False,
        "opening_time": "09:00",
        "closing_time": "17:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general", "mental_health"],
    },
    {
        "name": "East York Medical Associates",
        "type": "clinic",
        "address": "1200 Pape Ave",
        "city": "Toronto",
        "latitude": 43.6912,
        "longitude": -79.3521,
        "phone": "416-421-2222",
        "is_open_24_7": False,
        "opening_time": "08:30",
        "closing_time": "17:30",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    {
        "name": "Scarborough Family Health",
        "type": "clinic",
        "address": "2660 Eglinton Ave E",
        "city": "Scarborough",
        "latitude": 43.7312,
        "longitude": -79.2621,
        "phone": "416-431-9000",
        "is_open_24_7": False,
        "opening_time": "09:00",
        "closing_time": "17:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general", "pediatric"],
    },
    {
        "name": "Brampton Community Health Centre",
        "type": "clinic",
        "address": "40 Finchgate Blvd",
        "city": "Brampton",
        "latitude": 43.7121,
        "longitude": -79.7621,
        "phone": "905-454-4777",
        "is_open_24_7": False,
        "opening_time": "09:00",
        "closing_time": "17:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general", "mental_health"],
    },
    {
        "name": "Downtown Medical Centre",
        "type": "clinic",
        "address": "250 Dundas St W",
        "city": "Toronto",
        "latitude": 43.6521,
        "longitude": -79.3821,
        "phone": "416-591-9999",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "18:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    # ── More Pharmacies ──────────────────────────────────────────────────────
    {
        "name": "Shoppers Drug Mart — Bloor & Spadina",
        "type": "pharmacy",
        "address": "711 Bloor St W",
        "city": "Toronto",
        "latitude": 43.6642,
        "longitude": -79.4121,
        "phone": "416-538-2311",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "22:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    {
        "name": "Shoppers Drug Mart — Scarborough Town Centre",
        "type": "pharmacy",
        "address": "300 Borough Dr",
        "city": "Scarborough",
        "latitude": 43.7734,
        "longitude": -79.2521,
        "phone": "416-296-0677",
        "is_open_24_7": False,
        "opening_time": "09:00",
        "closing_time": "21:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    {
        "name": "Rexall — Mississauga Square One",
        "type": "pharmacy",
        "address": "100 City Centre Dr",
        "city": "Mississauga",
        "latitude": 43.5921,
        "longitude": -79.6421,
        "phone": "905-273-3333",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "22:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    {
        "name": "Loblaws Pharmacy — Maple Leaf Gardens",
        "type": "pharmacy",
        "address": "60 Carlton St",
        "city": "Toronto",
        "latitude": 43.6621,
        "longitude": -79.3782,
        "phone": "416-924-9521",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "22:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    {
        "name": "Guardian Pharmacy — Etobicoke",
        "type": "pharmacy",
        "address": "1540 The Queensway",
        "city": "Etobicoke",
        "latitude": 43.6312,
        "longitude": -79.5321,
        "phone": "416-252-6666",
        "is_open_24_7": False,
        "opening_time": "09:00",
        "closing_time": "21:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    # ── Waterloo Region — Hospitals / ER ──────────────────────────────────────
    {
        "name": "Grand River Hospital",
        "type": "hospital",
        "address": "835 King St W",
        "city": "Kitchener",
        "latitude": 43.4489,
        "longitude": -80.4922,
        "phone": "519-749-4300",
        "is_open_24_7": True,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["general", "cardiac", "trauma", "respiratory"],
    },
    {
        "name": "St. Mary's General Hospital",
        "type": "hospital",
        "address": "911 Queen's Blvd",
        "city": "Kitchener",
        "latitude": 43.4512,
        "longitude": -80.4689,
        "phone": "519-744-3311",
        "is_open_24_7": True,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["general", "cardiac", "trauma"],
    },
    {
        "name": "Cambridge Memorial Hospital",
        "type": "hospital",
        "address": "700 Coronation Blvd",
        "city": "Cambridge",
        "latitude": 43.3612,
        "longitude": -80.3145,
        "phone": "519-621-2330",
        "is_open_24_7": True,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["general", "trauma", "orthopedic"],
    },
    {
        "name": "Guelph General Hospital",
        "type": "hospital",
        "address": "115 Delhi St",
        "city": "Guelph",
        "latitude": 43.5442,
        "longitude": -80.2489,
        "phone": "519-837-6440",
        "is_open_24_7": True,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["general", "pediatric", "respiratory"],
    },
    {
        "name": "Freeport Health Campus (Grand River)",
        "type": "hospital",
        "address": "3570 King St E",
        "city": "Kitchener",
        "latitude": 43.4212,
        "longitude": -80.3821,
        "phone": "519-749-4300",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "20:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general", "mental_health", "rehabilitation"],
    },
    # ── Waterloo Region — Urgent Care / Walk-in ───────────────────────────────
    {
        "name": "Waterloo Walk-in Clinic — University Plaza",
        "type": "urgent_care",
        "address": "170 University Ave W",
        "city": "Waterloo",
        "latitude": 43.4689,
        "longitude": -80.5221,
        "phone": "519-886-5555",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "20:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general", "pediatric"],
    },
    {
        "name": "Kitchener Urgent Care — Fairway",
        "type": "urgent_care",
        "address": "385 Fairway Rd S",
        "city": "Kitchener",
        "latitude": 43.4212,
        "longitude": -80.4521,
        "phone": "519-579-5555",
        "is_open_24_7": False,
        "opening_time": "09:00",
        "closing_time": "21:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    {
        "name": "Laurel Creek Urgent Care",
        "type": "urgent_care",
        "address": "650 Laurelwood Dr",
        "city": "Waterloo",
        "latitude": 43.4921,
        "longitude": -80.5121,
        "phone": "519-886-8888",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "20:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general", "respiratory"],
    },
    {
        "name": "Cambridge Urgent Care — Hespeler",
        "type": "urgent_care",
        "address": "500 Franklin Blvd",
        "city": "Cambridge",
        "latitude": 43.4212,
        "longitude": -80.3121,
        "phone": "519-654-5555",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "22:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    {
        "name": "Guelph Walk-in Medical Clinic",
        "type": "urgent_care",
        "address": "104 Wyndham St N",
        "city": "Guelph",
        "latitude": 43.5489,
        "longitude": -80.2489,
        "phone": "519-822-2222",
        "is_open_24_7": False,
        "opening_time": "09:00",
        "closing_time": "17:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general", "pediatric"],
    },
    {
        "name": "Uptown Waterloo Medical Walk-in",
        "type": "urgent_care",
        "address": "75 King St S",
        "city": "Waterloo",
        "latitude": 43.4642,
        "longitude": -80.5189,
        "phone": "519-888-1234",
        "is_open_24_7": False,
        "opening_time": "08:30",
        "closing_time": "19:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general", "mental_health"],
    },
    # ── Waterloo Region — Clinics ────────────────────────────────────────────
    {
        "name": "UW Campus Health Services",
        "type": "clinic",
        "address": "200 University Ave W",
        "city": "Waterloo",
        "latitude": 43.4702,
        "longitude": -80.5412,
        "phone": "519-888-4096",
        "is_open_24_7": False,
        "opening_time": "08:30",
        "closing_time": "16:30",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general", "pediatric", "mental_health"],
    },
    {
        "name": "Laurier Student Health",
        "type": "clinic",
        "address": "75 University Ave W",
        "city": "Waterloo",
        "latitude": 43.4662,
        "longitude": -80.5252,
        "phone": "519-884-0710",
        "is_open_24_7": False,
        "opening_time": "09:00",
        "closing_time": "16:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general", "mental_health"],
    },
    {
        "name": "Waterloo North Family Health",
        "type": "clinic",
        "address": "500 Parkside Dr",
        "city": "Waterloo",
        "latitude": 43.4821,
        "longitude": -80.5321,
        "phone": "519-886-5550",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "17:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general", "pediatric"],
    },
    {
        "name": "Kitchener Downtown Community Health",
        "type": "clinic",
        "address": "44 Francis St S",
        "city": "Kitchener",
        "latitude": 43.4512,
        "longitude": -80.4889,
        "phone": "519-576-1000",
        "is_open_24_7": False,
        "opening_time": "09:00",
        "closing_time": "17:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general", "mental_health"],
    },
    {
        "name": "Cambridge Family Medicine",
        "type": "clinic",
        "address": "150 Main St",
        "city": "Cambridge",
        "latitude": 43.3589,
        "longitude": -80.3121,
        "phone": "519-621-3333",
        "is_open_24_7": False,
        "opening_time": "08:30",
        "closing_time": "17:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    {
        "name": "Conestoga College Health Services",
        "type": "clinic",
        "address": "299 Doon Valley Dr",
        "city": "Kitchener",
        "latitude": 43.3912,
        "longitude": -80.4121,
        "phone": "519-748-5220",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "16:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    # ── Waterloo Region — Pharmacies ──────────────────────────────────────────
    {
        "name": "Shoppers Drug Mart — Waterloo Uptown",
        "type": "pharmacy",
        "address": "75 King St S",
        "city": "Waterloo",
        "latitude": 43.4642,
        "longitude": -80.5192,
        "phone": "519-886-1111",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "22:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    {
        "name": "Shoppers Drug Mart — University & Weber",
        "type": "pharmacy",
        "address": "255 Weber St N",
        "city": "Waterloo",
        "latitude": 43.4721,
        "longitude": -80.5121,
        "phone": "519-886-2222",
        "is_open_24_7": True,
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    {
        "name": "Rexall — Kitchener Downtown",
        "type": "pharmacy",
        "address": "150 King St W",
        "city": "Kitchener",
        "latitude": 43.4512,
        "longitude": -80.4821,
        "phone": "519-579-3333",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "21:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    {
        "name": "Shoppers Drug Mart — Cambridge Centre",
        "type": "pharmacy",
        "address": "355 Hespeler Rd",
        "city": "Cambridge",
        "latitude": 43.3912,
        "longitude": -80.3121,
        "phone": "519-623-4444",
        "is_open_24_7": False,
        "opening_time": "09:00",
        "closing_time": "21:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    {
        "name": "Rexall — Guelph Stone Road",
        "type": "pharmacy",
        "address": "485 Stone Rd E",
        "city": "Guelph",
        "latitude": 43.5121,
        "longitude": -80.2289,
        "phone": "519-824-5555",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "22:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    {
        "name": "Guardian Pharmacy — Waterloo Boardwalk",
        "type": "pharmacy",
        "address": "330 The Boardwalk",
        "city": "Waterloo",
        "latitude": 43.4589,
        "longitude": -80.4989,
        "phone": "519-886-6666",
        "is_open_24_7": False,
        "opening_time": "09:00",
        "closing_time": "21:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    {
        "name": "Shoppers Drug Mart — Kitchener Fairway",
        "type": "pharmacy",
        "address": "2960 Kingsway Dr",
        "city": "Kitchener",
        "latitude": 43.4212,
        "longitude": -80.4521,
        "phone": "519-579-7777",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "22:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
]

LIVE_STATUS_PRESETS = {
    "hospital": {"wait_range": (30, 180), "capacity_range": (0.5, 0.95)},
    "er":       {"wait_range": (45, 240), "capacity_range": (0.6, 1.0)},
    "urgent_care": {"wait_range": (10, 60),  "capacity_range": (0.2, 0.75)},
    "clinic":   {"wait_range": (5, 40),   "capacity_range": (0.1, 0.6)},
    "pharmacy": {"wait_range": (0, 10),   "capacity_range": (0.0, 0.3)},
}


def seed(reset: bool = False):
    db = SessionLocal()
    try:
        if db.query(models.CareLocation).count() > 0:
            if not reset:
                print("Database already seeded — skipping. Use --reset to wipe and reseed.")
                return
            # Wipe in order (FKs: references to care_locations first)
            db.query(models.RoutingRecommendation).delete()
            db.query(models.Handoff).delete()
            db.query(models.Alert).delete()
            db.query(models.VisitOutcome).delete()
            db.query(models.LiveStatus).delete()
            db.query(models.LocationSpecialty).delete()
            db.query(models.CareLocation).delete()
            db.commit()
            db = SessionLocal()

        for loc_data in CARE_LOCATIONS:
            specialties = loc_data.pop("specialties", [])

            location = models.CareLocation(**loc_data)
            db.add(location)
            db.flush()  # get the auto-generated id

            for specialty in specialties:
                db.add(models.LocationSpecialty(
                    care_location_id=location.id,
                    specialty_name=specialty,
                ))

            preset = LIVE_STATUS_PRESETS.get(location.type, LIVE_STATUS_PRESETS["clinic"])
            current_wait = random.randint(*preset["wait_range"])
            capacity = round(random.uniform(*preset["capacity_range"]), 2)

            db.add(models.LiveStatus(
                care_location_id=location.id,
                current_wait_mins=current_wait,
                predicted_wait_on_arrival_mins=max(0, current_wait + random.randint(-10, 20)),
                capacity_score=capacity,
                queue_length=int(capacity * random.randint(5, 30)),
                staffing_level=random.choice(["low", "normal", "normal", "high"]),
                ambulance_load=random.randint(0, 3) if location.accepts_ambulance else 0,
                last_updated_at=datetime.now(timezone.utc),
            ))

        db.commit()
        print(f"Seeded {len(CARE_LOCATIONS)} care locations with live status.")
    except Exception as exc:
        db.rollback()
        raise exc
    finally:
        db.close()


if __name__ == "__main__":
    seed(reset="--reset" in sys.argv)
