"""
Seed script - run once to populate the database with Toronto-area care locations
and simulated live status data.

Usage:
    python seed.py           # seed if DB is empty
    python seed.py --reset   # wipe locations and reseed with full list
"""
import random
import sys
from datetime import datetime, timezone
from database import engine, SessionLocal, Base
import models  # noqa: F401 - registers all models with Base
import wait_times.models  # noqa: F401 - registers wait time models with Base
from wait_times.service import refresh_wait_times_for_locations

Base.metadata.create_all(bind=engine)

CARE_LOCATIONS = [
    # ── Hospitals / ERs ──────────────────────────────────────────────────────
    {
        "name": "Toronto General Hospital",
        "type": "hospital",
        "address": "200 Elizabeth St",
        "city": "Toronto",
        "latitude": 43.6594,
        "longitude": -79.3883,
        "phone": "416-340-4800",
        "is_open_24_7": True,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["cardiac", "trauma", "general", "respiratory"],
    },
    {
        "name": "St. Michael's Hospital ER",
        "type": "er",
        "address": "36 Queen St E",
        "city": "Toronto",
        "latitude": 43.6534,
        "longitude": -79.3762,
        "phone": "416-360-4000",
        "is_open_24_7": True,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["trauma", "general", "cardiac"],
    },
    {
        "name": "Sunnybrook Health Sciences Centre",
        "type": "hospital",
        "address": "2075 Bayview Ave",
        "city": "Toronto",
        "latitude": 43.7232,
        "longitude": -79.3765,
        "phone": "416-480-6100",
        "is_open_24_7": True,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["trauma", "cardiac", "orthopedic", "general"],
    },
    {
        "name": "SickKids Hospital",
        "type": "hospital",
        "address": "555 University Ave",
        "city": "Toronto",
        "latitude": 43.6574,
        "longitude": -79.3902,
        "phone": "416-813-1500",
        "is_open_24_7": True,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["pediatric", "general"],
    },
    {
        "name": "Mount Sinai Hospital",
        "type": "hospital",
        "address": "600 University Ave",
        "city": "Toronto",
        "latitude": 43.6573,
        "longitude": -79.3906,
        "phone": "416-596-4200",
        "is_open_24_7": True,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["general", "respiratory", "cardiac"],
    },
    {
        "name": "North York General Hospital",
        "type": "hospital",
        "address": "4001 Leslie St",
        "city": "North York",
        "latitude": 43.7614,
        "longitude": -79.3437,
        "phone": "416-756-6000",
        "is_open_24_7": True,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["general", "trauma", "orthopedic"],
    },
    {
        "name": "Humber River Hospital",
        "type": "hospital",
        "address": "1235 Wilson Ave",
        "city": "North York",
        "latitude": 43.7433,
        "longitude": -79.5021,
        "phone": "416-242-1000",
        "is_open_24_7": True,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["general", "cardiac"],
    },
    {
        "name": "Scarborough Health Network - General",
        "type": "hospital",
        "address": "3050 Lawrence Ave E",
        "city": "Scarborough",
        "latitude": 43.7552,
        "longitude": -79.2411,
        "phone": "416-431-8200",
        "is_open_24_7": True,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["general", "trauma", "respiratory"],
    },
    # ── Urgent Care ───────────────────────────────────────────────────────────
    {
        "name": "Appletree Medical Group - King West",
        "type": "urgent_care",
        "address": "680 King St W",
        "city": "Toronto",
        "latitude": 43.6446,
        "longitude": -79.4023,
        "phone": "416-593-2273",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "20:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    {
        "name": "Medpoint Health Centres - Yonge & Eg",
        "type": "urgent_care",
        "address": "2300 Yonge St",
        "city": "Toronto",
        "latitude": 43.7053,
        "longitude": -79.3979,
        "phone": "416-932-9000",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "22:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general", "respiratory"],
    },
    {
        "name": "Bay-College Medical Centre",
        "type": "urgent_care",
        "address": "777 Bay St",
        "city": "Toronto",
        "latitude": 43.6591,
        "longitude": -79.3842,
        "phone": "416-977-7653",
        "is_open_24_7": False,
        "opening_time": "09:00",
        "closing_time": "21:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general", "mental_health"],
    },
    # ── Walk-in Clinics ───────────────────────────────────────────────────────
    {
        "name": "Women's College Hospital Walk-in",
        "type": "clinic",
        "address": "76 Grenville St",
        "city": "Toronto",
        "latitude": 43.6640,
        "longitude": -79.3880,
        "phone": "416-323-6400",
        "is_open_24_7": False,
        "opening_time": "08:30",
        "closing_time": "17:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    {
        "name": "Rexdale Community Health Centre",
        "type": "clinic",
        "address": "8 Taber Rd",
        "city": "Etobicoke",
        "latitude": 43.7306,
        "longitude": -79.5744,
        "phone": "416-744-0066",
        "is_open_24_7": False,
        "opening_time": "09:00",
        "closing_time": "17:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general", "mental_health"],
    },
    # ── Pharmacies ────────────────────────────────────────────────────────────
    {
        "name": "Shoppers Drug Mart - Yonge & Dundas",
        "type": "pharmacy",
        "address": "700 Yonge St",
        "city": "Toronto",
        "latitude": 43.6672,
        "longitude": -79.3860,
        "phone": "416-961-0707",
        "is_open_24_7": True,
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    {
        "name": "Rexall Pharmacy - Bay St",
        "type": "pharmacy",
        "address": "100 Bay St",
        "city": "Toronto",
        "latitude": 43.6489,
        "longitude": -79.3800,
        "phone": "416-368-4400",
        "is_open_24_7": False,
        "opening_time": "07:00",
        "closing_time": "23:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    # ── More Hospitals / ERs (GTA) ───────────────────────────────────────────
    {
        "name": "Michael Garron Hospital",
        "type": "hospital",
        "address": "825 Coxwell Ave",
        "city": "Toronto",
        "latitude": 43.6892,
        "longitude": -79.3134,
        "phone": "416-469-6000",
        "is_open_24_7": True,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["general", "respiratory", "cardiac"],
    },
    {
        "name": "Credit Valley Hospital",
        "type": "hospital",
        "address": "2200 Eglinton Ave W",
        "city": "Mississauga",
        "latitude": 43.5621,
        "longitude": -79.6762,
        "phone": "905-813-2200",
        "is_open_24_7": True,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["general", "trauma", "pediatric"],
    },
    {
        "name": "Trillium Health Partners - Mississauga",
        "type": "hospital",
        "address": "100 Queensway W",
        "city": "Mississauga",
        "latitude": 43.5892,
        "longitude": -79.6431,
        "phone": "905-848-7100",
        "is_open_24_7": True,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["general", "cardiac", "trauma"],
    },
    {
        "name": "William Osler Health - Brampton Civic",
        "type": "hospital",
        "address": "2100 Bovaird Dr E",
        "city": "Brampton",
        "latitude": 43.7312,
        "longitude": -79.7621,
        "phone": "905-494-2120",
        "is_open_24_7": True,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["general", "trauma", "pediatric"],
    },
    {
        "name": "Rouge Valley Health - Centenary",
        "type": "hospital",
        "address": "2867 Ellesmere Rd",
        "city": "Scarborough",
        "latitude": 43.7734,
        "longitude": -79.2134,
        "phone": "416-284-8131",
        "is_open_24_7": True,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["general", "respiratory"],
    },
    {
        "name": "Mackenzie Health - Richmond Hill",
        "type": "hospital",
        "address": "10 Trench St",
        "city": "Richmond Hill",
        "latitude": 43.8821,
        "longitude": -79.4421,
        "phone": "905-883-1212",
        "is_open_24_7": True,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["general", "cardiac", "orthopedic"],
    },
    {
        "name": "Markham Stouffville Hospital",
        "type": "hospital",
        "address": "381 Church St",
        "city": "Markham",
        "latitude": 43.8765,
        "longitude": -79.2612,
        "phone": "905-472-7000",
        "is_open_24_7": True,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["general", "pediatric", "trauma"],
    },
    {
        "name": "Oakville Trafalgar Memorial Hospital",
        "type": "hospital",
        "address": "327 Reynolds St",
        "city": "Oakville",
        "latitude": 43.4521,
        "longitude": -79.6912,
        "phone": "905-845-2571",
        "is_open_24_7": True,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["general", "cardiac", "respiratory"],
    },
    # ── More Urgent Care / Walk-in ────────────────────────────────────────────
    {
        "name": "Appletree Medical - Queen West",
        "type": "urgent_care",
        "address": "798 Queen St W",
        "city": "Toronto",
        "latitude": 43.6451,
        "longitude": -79.4123,
        "phone": "416-703-6666",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "20:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    {
        "name": "Toronto Western Hospital Urgent Care",
        "type": "urgent_care",
        "address": "399 Bathurst St",
        "city": "Toronto",
        "latitude": 43.6542,
        "longitude": -79.4021,
        "phone": "416-603-2580",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "22:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general", "orthopedic"],
    },
    {
        "name": "Medpoint - Bloor & Bathurst",
        "type": "urgent_care",
        "address": "701 Bloor St W",
        "city": "Toronto",
        "latitude": 43.6642,
        "longitude": -79.4182,
        "phone": "416-532-9000",
        "is_open_24_7": False,
        "opening_time": "09:00",
        "closing_time": "21:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general", "respiratory"],
    },
    {
        "name": "Sheridan Walk-in Clinic",
        "type": "urgent_care",
        "address": "2225 Sheppard Ave E",
        "city": "North York",
        "latitude": 43.7721,
        "longitude": -79.3821,
        "phone": "416-491-5555",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "20:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general", "pediatric"],
    },
    {
        "name": "Mississauga Urgent Care - Hurontario",
        "type": "urgent_care",
        "address": "3180 Hurontario St",
        "city": "Mississauga",
        "latitude": 43.5812,
        "longitude": -79.6421,
        "phone": "905-276-8888",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "22:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    # ── More Clinics ──────────────────────────────────────────────────────────
    {
        "name": "Crossways Clinic",
        "type": "clinic",
        "address": "2340 Dundas St W",
        "city": "Toronto",
        "latitude": 43.6621,
        "longitude": -79.4521,
        "phone": "416-604-9898",
        "is_open_24_7": False,
        "opening_time": "09:00",
        "closing_time": "17:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general", "mental_health"],
    },
    {
        "name": "East York Medical Associates",
        "type": "clinic",
        "address": "1200 Pape Ave",
        "city": "Toronto",
        "latitude": 43.6912,
        "longitude": -79.3521,
        "phone": "416-421-2222",
        "is_open_24_7": False,
        "opening_time": "08:30",
        "closing_time": "17:30",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    {
        "name": "Scarborough Family Health",
        "type": "clinic",
        "address": "2660 Eglinton Ave E",
        "city": "Scarborough",
        "latitude": 43.7312,
        "longitude": -79.2621,
        "phone": "416-431-9000",
        "is_open_24_7": False,
        "opening_time": "09:00",
        "closing_time": "17:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general", "pediatric"],
    },
    {
        "name": "Brampton Community Health Centre",
        "type": "clinic",
        "address": "40 Finchgate Blvd",
        "city": "Brampton",
        "latitude": 43.7121,
        "longitude": -79.7621,
        "phone": "905-454-4777",
        "is_open_24_7": False,
        "opening_time": "09:00",
        "closing_time": "17:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general", "mental_health"],
    },
    {
        "name": "Downtown Medical Centre",
        "type": "clinic",
        "address": "250 Dundas St W",
        "city": "Toronto",
        "latitude": 43.6521,
        "longitude": -79.3821,
        "phone": "416-591-9999",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "18:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    # ── More Pharmacies ──────────────────────────────────────────────────────
    {
        "name": "Shoppers Drug Mart - Bloor & Spadina",
        "type": "pharmacy",
        "address": "711 Bloor St W",
        "city": "Toronto",
        "latitude": 43.6642,
        "longitude": -79.4121,
        "phone": "416-538-2311",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "22:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    {
        "name": "Shoppers Drug Mart - Scarborough Town Centre",
        "type": "pharmacy",
        "address": "300 Borough Dr",
        "city": "Scarborough",
        "latitude": 43.7734,
        "longitude": -79.2521,
        "phone": "416-296-0677",
        "is_open_24_7": False,
        "opening_time": "09:00",
        "closing_time": "21:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    {
        "name": "Rexall - Mississauga Square One",
        "type": "pharmacy",
        "address": "100 City Centre Dr",
        "city": "Mississauga",
        "latitude": 43.5921,
        "longitude": -79.6421,
        "phone": "905-273-3333",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "22:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    {
        "name": "Loblaws Pharmacy - Maple Leaf Gardens",
        "type": "pharmacy",
        "address": "60 Carlton St",
        "city": "Toronto",
        "latitude": 43.6621,
        "longitude": -79.3782,
        "phone": "416-924-9521",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "22:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    {
        "name": "Guardian Pharmacy - Etobicoke",
        "type": "pharmacy",
        "address": "1540 The Queensway",
        "city": "Etobicoke",
        "latitude": 43.6312,
        "longitude": -79.5321,
        "phone": "416-252-6666",
        "is_open_24_7": False,
        "opening_time": "09:00",
        "closing_time": "21:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    # ── Waterloo Region - Hospitals / ER ──────────────────────────────────────
    {
        "name": "Grand River Hospital",
        "type": "hospital",
        "address": "835 King St W",
        "city": "Kitchener",
        "latitude": 43.4489,
        "longitude": -80.4922,
        "phone": "519-749-4300",
        "is_open_24_7": True,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["general", "cardiac", "trauma", "respiratory"],
    },
    {
        "name": "St. Mary's General Hospital",
        "type": "hospital",
        "address": "911 Queen's Blvd",
        "city": "Kitchener",
        "latitude": 43.4512,
        "longitude": -80.4689,
        "phone": "519-744-3311",
        "is_open_24_7": True,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["general", "cardiac", "trauma"],
    },
    {
        "name": "Cambridge Memorial Hospital",
        "type": "hospital",
        "address": "700 Coronation Blvd",
        "city": "Cambridge",
        "latitude": 43.3612,
        "longitude": -80.3145,
        "phone": "519-621-2330",
        "is_open_24_7": True,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["general", "trauma", "orthopedic"],
    },
    {
        "name": "Guelph General Hospital",
        "type": "hospital",
        "address": "115 Delhi St",
        "city": "Guelph",
        "latitude": 43.5442,
        "longitude": -80.2489,
        "phone": "519-837-6440",
        "is_open_24_7": True,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["general", "pediatric", "respiratory"],
    },
    {
        "name": "Freeport Health Campus (Grand River)",
        "type": "hospital",
        "address": "3570 King St E",
        "city": "Kitchener",
        "latitude": 43.4212,
        "longitude": -80.3821,
        "phone": "519-749-4300",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "20:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general", "mental_health", "rehabilitation"],
    },
    # ── Waterloo Region - Urgent Care / Walk-in ───────────────────────────────
    {
        "name": "Waterloo Walk-in Clinic - University Plaza",
        "type": "urgent_care",
        "address": "170 University Ave W",
        "city": "Waterloo",
        "latitude": 43.4689,
        "longitude": -80.5221,
        "phone": "519-886-5555",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "20:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general", "pediatric"],
    },
    {
        "name": "Kitchener Urgent Care - Fairway",
        "type": "urgent_care",
        "address": "385 Fairway Rd S",
        "city": "Kitchener",
        "latitude": 43.4212,
        "longitude": -80.4521,
        "phone": "519-579-5555",
        "is_open_24_7": False,
        "opening_time": "09:00",
        "closing_time": "21:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    {
        "name": "Laurel Creek Urgent Care",
        "type": "urgent_care",
        "address": "650 Laurelwood Dr",
        "city": "Waterloo",
        "latitude": 43.4921,
        "longitude": -80.5121,
        "phone": "519-886-8888",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "20:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general", "respiratory"],
    },
    {
        "name": "Cambridge Urgent Care - Hespeler",
        "type": "urgent_care",
        "address": "500 Franklin Blvd",
        "city": "Cambridge",
        "latitude": 43.4212,
        "longitude": -80.3121,
        "phone": "519-654-5555",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "22:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    {
        "name": "Guelph Walk-in Medical Clinic",
        "type": "urgent_care",
        "address": "104 Wyndham St N",
        "city": "Guelph",
        "latitude": 43.5489,
        "longitude": -80.2489,
        "phone": "519-822-2222",
        "is_open_24_7": False,
        "opening_time": "09:00",
        "closing_time": "17:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general", "pediatric"],
    },
    {
        "name": "Uptown Waterloo Medical Walk-in",
        "type": "urgent_care",
        "address": "75 King St S",
        "city": "Waterloo",
        "latitude": 43.4642,
        "longitude": -80.5189,
        "phone": "519-888-1234",
        "is_open_24_7": False,
        "opening_time": "08:30",
        "closing_time": "19:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general", "mental_health"],
    },
    # ── Waterloo Region - Clinics ────────────────────────────────────────────
    {
        "name": "UW Campus Health Services",
        "type": "clinic",
        "address": "200 University Ave W",
        "city": "Waterloo",
        "latitude": 43.4702,
        "longitude": -80.5412,
        "phone": "519-888-4096",
        "is_open_24_7": False,
        "opening_time": "08:30",
        "closing_time": "16:30",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general", "pediatric", "mental_health"],
    },
    {
        "name": "Laurier Student Health",
        "type": "clinic",
        "address": "75 University Ave W",
        "city": "Waterloo",
        "latitude": 43.4662,
        "longitude": -80.5252,
        "phone": "519-884-0710",
        "is_open_24_7": False,
        "opening_time": "09:00",
        "closing_time": "16:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general", "mental_health"],
    },
    {
        "name": "Waterloo North Family Health",
        "type": "clinic",
        "address": "500 Parkside Dr",
        "city": "Waterloo",
        "latitude": 43.4821,
        "longitude": -80.5321,
        "phone": "519-886-5550",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "17:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general", "pediatric"],
    },
    {
        "name": "Kitchener Downtown Community Health",
        "type": "clinic",
        "address": "44 Francis St S",
        "city": "Kitchener",
        "latitude": 43.4512,
        "longitude": -80.4889,
        "phone": "519-576-1000",
        "is_open_24_7": False,
        "opening_time": "09:00",
        "closing_time": "17:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general", "mental_health"],
    },
    {
        "name": "Cambridge Family Medicine",
        "type": "clinic",
        "address": "150 Main St",
        "city": "Cambridge",
        "latitude": 43.3589,
        "longitude": -80.3121,
        "phone": "519-621-3333",
        "is_open_24_7": False,
        "opening_time": "08:30",
        "closing_time": "17:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    {
        "name": "Conestoga College Health Services",
        "type": "clinic",
        "address": "299 Doon Valley Dr",
        "city": "Kitchener",
        "latitude": 43.3912,
        "longitude": -80.4121,
        "phone": "519-748-5220",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "16:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    # ── Waterloo Region - Pharmacies ──────────────────────────────────────────
    {
        "name": "Shoppers Drug Mart - Waterloo Uptown",
        "type": "pharmacy",
        "address": "75 King St S",
        "city": "Waterloo",
        "latitude": 43.4642,
        "longitude": -80.5192,
        "phone": "519-886-1111",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "22:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    {
        "name": "Shoppers Drug Mart - University & Weber",
        "type": "pharmacy",
        "address": "255 Weber St N",
        "city": "Waterloo",
        "latitude": 43.4721,
        "longitude": -80.5121,
        "phone": "519-886-2222",
        "is_open_24_7": True,
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    {
        "name": "Rexall - Kitchener Downtown",
        "type": "pharmacy",
        "address": "150 King St W",
        "city": "Kitchener",
        "latitude": 43.4512,
        "longitude": -80.4821,
        "phone": "519-579-3333",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "21:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    {
        "name": "Shoppers Drug Mart - Cambridge Centre",
        "type": "pharmacy",
        "address": "355 Hespeler Rd",
        "city": "Cambridge",
        "latitude": 43.3912,
        "longitude": -80.3121,
        "phone": "519-623-4444",
        "is_open_24_7": False,
        "opening_time": "09:00",
        "closing_time": "21:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    {
        "name": "Rexall - Guelph Stone Road",
        "type": "pharmacy",
        "address": "485 Stone Rd E",
        "city": "Guelph",
        "latitude": 43.5121,
        "longitude": -80.2289,
        "phone": "519-824-5555",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "22:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    {
        "name": "Guardian Pharmacy - Waterloo Boardwalk",
        "type": "pharmacy",
        "address": "330 The Boardwalk",
        "city": "Waterloo",
        "latitude": 43.4589,
        "longitude": -80.4989,
        "phone": "519-886-6666",
        "is_open_24_7": False,
        "opening_time": "09:00",
        "closing_time": "21:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    {
        "name": "Shoppers Drug Mart - Kitchener Fairway",
        "type": "pharmacy",
        "address": "2960 Kingsway Dr",
        "city": "Kitchener",
        "latitude": 43.4212,
        "longitude": -80.4521,
        "phone": "519-579-7777",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "22:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    # ── Hamilton / Halton / Brantford region ─────────────────────────────────
    {
        "name": "Hamilton General Hospital",
        "type": "hospital",
        "address": "237 Barton St E",
        "city": "Hamilton",
        "latitude": 43.2621,
        "longitude": -79.8562,
        "phone": "905-527-4322",
        "is_open_24_7": True,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["cardiac", "trauma", "general", "respiratory"],
    },
    {
        "name": "St. Joseph's Healthcare Hamilton - Charlton",
        "type": "hospital",
        "address": "50 Charlton Ave E",
        "city": "Hamilton",
        "latitude": 43.2489,
        "longitude": -79.8701,
        "phone": "905-522-1155",
        "is_open_24_7": True,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["general", "mental_health", "respiratory"],
    },
    {
        "name": "Juravinski Hospital",
        "type": "hospital",
        "address": "711 Concession St",
        "city": "Hamilton",
        "latitude": 43.2312,
        "longitude": -79.8421,
        "phone": "905-521-2100",
        "is_open_24_7": True,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["general", "cardiac", "orthopedic"],
    },
    {
        "name": "McMaster Children's Hospital",
        "type": "hospital",
        "address": "1280 Main St W",
        "city": "Hamilton",
        "latitude": 43.2589,
        "longitude": -79.9162,
        "phone": "905-521-2100",
        "is_open_24_7": True,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["pediatric", "general"],
    },
    {
        "name": "Joseph Brant Hospital",
        "type": "hospital",
        "address": "1230 North Shore Blvd E",
        "city": "Burlington",
        "latitude": 43.3412,
        "longitude": -79.7921,
        "phone": "905-632-3737",
        "is_open_24_7": True,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["general", "cardiac", "trauma"],
    },
    {
        "name": "Brant Community Healthcare - Brantford General",
        "type": "hospital",
        "address": "200 Terrace Hill St",
        "city": "Brantford",
        "latitude": 43.1412,
        "longitude": -80.2621,
        "phone": "519-752-7871",
        "is_open_24_7": True,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["general", "trauma", "respiratory"],
    },
    {
        "name": "Hamilton Urgent Care - Stone Church",
        "type": "urgent_care",
        "address": "1595 Stone Church Rd E",
        "city": "Hamilton",
        "latitude": 43.2089,
        "longitude": -79.8312,
        "phone": "905-318-8888",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "22:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general", "pediatric"],
    },
    {
        "name": "Burlington Urgent Care - Appleby",
        "type": "urgent_care",
        "address": "4050 Palladium Way",
        "city": "Burlington",
        "latitude": 43.3721,
        "longitude": -79.8421,
        "phone": "905-319-9999",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "21:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },

    # ── London, ON ────────────────────────────────────────────────────────────
    {
        "name": "London Health Sciences - Victoria Hospital",
        "type": "hospital",
        "address": "800 Commissioners Rd E",
        "city": "London",
        "latitude": 42.9652,
        "longitude": -81.2068,
        "phone": "519-685-8500",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "trauma", "cardiac", "oncology"],
    },
    {
        "name": "London Health Sciences - University Hospital",
        "type": "hospital",
        "address": "339 Windermere Rd",
        "city": "London",
        "latitude": 43.0084,
        "longitude": -81.2737,
        "phone": "519-663-3000",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "transplant", "neuroscience", "cardiac"],
    },
    {
        "name": "St. Joseph's Health Care London",
        "type": "hospital",
        "address": "268 Grosvenor St",
        "city": "London",
        "latitude": 42.9951,
        "longitude": -81.2510,
        "phone": "519-646-6100",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["mental_health", "addiction", "orthopedic", "general"],
    },
    {
        "name": "London Walk-in Urgent Care",
        "type": "urgent_care",
        "address": "450 Central Ave",
        "city": "London",
        "latitude": 42.9838,
        "longitude": -81.2454,
        "phone": "519-434-3010",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "21:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },

    # ── Windsor, ON ───────────────────────────────────────────────────────────
    {
        "name": "Windsor Regional Hospital - Metropolitan Campus",
        "type": "hospital",
        "address": "1995 Lens Ave",
        "city": "Windsor",
        "latitude": 42.3091,
        "longitude": -83.0387,
        "phone": "519-254-5577",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "cardiac", "trauma", "oncology"],
    },
    {
        "name": "Windsor Regional Hospital - Ouellette Campus",
        "type": "hospital",
        "address": "1030 Ouellette Ave",
        "city": "Windsor",
        "latitude": 42.3070,
        "longitude": -83.0350,
        "phone": "519-254-5577",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "women_health", "neonatal"],
    },
    {
        "name": "Windsor Urgent Care Clinic",
        "type": "urgent_care",
        "address": "3190 Sandwich St",
        "city": "Windsor",
        "latitude": 42.2981,
        "longitude": -83.0712,
        "phone": "519-255-2700",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "22:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },

    # ── Ottawa, ON ────────────────────────────────────────────────────────────
    {
        "name": "The Ottawa Hospital - General Campus",
        "type": "hospital",
        "address": "501 Smyth Rd",
        "city": "Ottawa",
        "latitude": 45.3939,
        "longitude": -75.6680,
        "phone": "613-722-7000",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "trauma", "cardiac", "cancer", "neuroscience"],
    },
    {
        "name": "The Ottawa Hospital - Civic Campus",
        "type": "hospital",
        "address": "1053 Carling Ave",
        "city": "Ottawa",
        "latitude": 45.3969,
        "longitude": -75.7465,
        "phone": "613-722-7000",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "cardiac", "orthopedic", "respiratory"],
    },
    {
        "name": "Children's Hospital of Eastern Ontario",
        "type": "hospital",
        "address": "401 Smyth Rd",
        "city": "Ottawa",
        "latitude": 45.3945,
        "longitude": -75.6692,
        "phone": "613-737-7600",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["pediatric", "emergency", "oncology", "cardiac"],
    },
    {
        "name": "Montfort Hospital",
        "type": "hospital",
        "address": "713 Montreal Rd",
        "city": "Ottawa",
        "latitude": 45.4436,
        "longitude": -75.6293,
        "phone": "613-746-4621",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "general", "orthopedic"],
    },
    {
        "name": "Ottawa Urgent Care - Merivale",
        "type": "urgent_care",
        "address": "1625 Merivale Rd",
        "city": "Ottawa",
        "latitude": 45.3583,
        "longitude": -75.7319,
        "phone": "613-226-6400",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "21:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    {
        "name": "Appletree Medical Group - Ottawa Baseline",
        "type": "clinic",
        "address": "1485 Baseline Rd",
        "city": "Ottawa",
        "latitude": 45.3748,
        "longitude": -75.7337,
        "phone": "613-225-7000",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "20:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general", "family"],
    },

    # ── St. Catharines / Niagara ──────────────────────────────────────────────
    {
        "name": "Niagara Health - St. Catharines Site",
        "type": "hospital",
        "address": "1200 Fourth Ave",
        "city": "St. Catharines",
        "latitude": 43.1604,
        "longitude": -79.2163,
        "phone": "905-684-7271",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "cardiac", "oncology", "orthopedic"],
    },
    {
        "name": "Niagara Health - Welland Site",
        "type": "hospital",
        "address": "65 Third St",
        "city": "Welland",
        "latitude": 42.9854,
        "longitude": -79.2487,
        "phone": "905-732-6111",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "general", "pediatric"],
    },
    {
        "name": "Niagara Health - Niagara Falls Site",
        "type": "hospital",
        "address": "5546 Portage Rd",
        "city": "Niagara Falls",
        "latitude": 43.0842,
        "longitude": -79.0695,
        "phone": "905-378-4647",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "general"],
    },

    # ── Sudbury, ON ───────────────────────────────────────────────────────────
    {
        "name": "Health Sciences North",
        "type": "hospital",
        "address": "41 Ramsey Lake Rd",
        "city": "Sudbury",
        "latitude": 46.4775,
        "longitude": -80.9638,
        "phone": "705-523-7100",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "cardiac", "cancer", "orthopedic", "trauma"],
    },
    {
        "name": "Sudbury Urgent Care",
        "type": "urgent_care",
        "address": "865 Notre-Dame Ave",
        "city": "Sudbury",
        "latitude": 46.4921,
        "longitude": -81.0004,
        "phone": "705-523-7700",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "21:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },

    # ── Kingston, ON ──────────────────────────────────────────────────────────
    {
        "name": "Kingston Health Sciences - Kingston General",
        "type": "hospital",
        "address": "76 Stuart St",
        "city": "Kingston",
        "latitude": 44.2265,
        "longitude": -76.4905,
        "phone": "613-548-3232",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "cardiac", "cancer", "transplant", "trauma"],
    },
    {
        "name": "Kingston Health Sciences - Hotel Dieu",
        "type": "hospital",
        "address": "166 Brock St",
        "city": "Kingston",
        "latitude": 44.2348,
        "longitude": -76.4877,
        "phone": "613-544-3310",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": False,
        "specialties": ["orthopedic", "rehabilitation", "urology", "general"],
    },
    {
        "name": "Kingston Urgent Care Clinic",
        "type": "urgent_care",
        "address": "1471 John Counter Blvd",
        "city": "Kingston",
        "latitude": 44.2491,
        "longitude": -76.5289,
        "phone": "613-389-5100",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "20:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },

    # ── Thunder Bay, ON ───────────────────────────────────────────────────────
    {
        "name": "Thunder Bay Regional Health Sciences Centre",
        "type": "hospital",
        "address": "980 Oliver Rd",
        "city": "Thunder Bay",
        "latitude": 48.4037,
        "longitude": -89.2703,
        "phone": "807-684-6000",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "cardiac", "cancer", "trauma", "orthopedic"],
    },

    # ── Barrie, ON ────────────────────────────────────────────────────────────
    {
        "name": "Royal Victoria Regional Health Centre",
        "type": "hospital",
        "address": "201 Georgian Dr",
        "city": "Barrie",
        "latitude": 44.3781,
        "longitude": -79.6820,
        "phone": "705-728-9090",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "cardiac", "orthopedic", "general"],
    },
    {
        "name": "Barrie Walk-in Medical Clinic",
        "type": "urgent_care",
        "address": "509 Dunlop St W",
        "city": "Barrie",
        "latitude": 44.3898,
        "longitude": -79.7021,
        "phone": "705-725-1766",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "20:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },

    # ── Guelph, ON ────────────────────────────────────────────────────────────
    {
        "name": "Guelph General Hospital",
        "type": "hospital",
        "address": "115 Delhi St",
        "city": "Guelph",
        "latitude": 43.5528,
        "longitude": -80.2490,
        "phone": "519-822-5350",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "cardiac", "orthopedic", "general"],
    },
    {
        "name": "Guelph Urgent Care Clinic",
        "type": "urgent_care",
        "address": "85 Westmount Rd",
        "city": "Guelph",
        "latitude": 43.5458,
        "longitude": -80.2631,
        "phone": "519-824-3921",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "21:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },

    # ── Oshawa / Durham Region, ON ────────────────────────────────────────────
    {
        "name": "Lakeridge Health - Oshawa",
        "type": "hospital",
        "address": "1 Hospital Ct",
        "city": "Oshawa",
        "latitude": 43.9063,
        "longitude": -78.8453,
        "phone": "905-576-8711",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "cardiac", "oncology", "general"],
    },
    {
        "name": "Lakeridge Health - Ajax-Pickering",
        "type": "hospital",
        "address": "580 Harwood Ave S",
        "city": "Ajax",
        "latitude": 43.8488,
        "longitude": -79.0254,
        "phone": "905-683-2320",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "general", "orthopedic"],
    },
    {
        "name": "Durham Urgent Care",
        "type": "urgent_care",
        "address": "1100 Champlain Ave",
        "city": "Oshawa",
        "latitude": 43.8915,
        "longitude": -78.8610,
        "phone": "905-433-4440",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "21:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },

    # ── Peterborough, ON ──────────────────────────────────────────────────────
    {
        "name": "Peterborough Regional Health Centre",
        "type": "hospital",
        "address": "1 Hospital Dr",
        "city": "Peterborough",
        "latitude": 44.3101,
        "longitude": -78.3197,
        "phone": "705-743-2121",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "cardiac", "cancer", "orthopedic"],
    },
    {
        "name": "Peterborough Urgent Care Clinic",
        "type": "urgent_care",
        "address": "689 The Kingsway",
        "city": "Peterborough",
        "latitude": 44.3021,
        "longitude": -78.3398,
        "phone": "705-741-5082",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "21:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },

    # ── Belleville, ON ────────────────────────────────────────────────────────
    {
        "name": "Belleville General Hospital",
        "type": "hospital",
        "address": "265 Dundas St E",
        "city": "Belleville",
        "latitude": 44.1681,
        "longitude": -77.3784,
        "phone": "613-969-7400",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "cardiac", "general"],
    },

    # ── Sault Ste. Marie, ON ──────────────────────────────────────────────────
    {
        "name": "Sault Area Hospital",
        "type": "hospital",
        "address": "750 Great Northern Rd",
        "city": "Sault Ste. Marie",
        "latitude": 46.5089,
        "longitude": -84.3440,
        "phone": "705-759-3434",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "cardiac", "cancer", "general"],
    },

    # ── Sarnia, ON ────────────────────────────────────────────────────────────
    {
        "name": "Bluewater Health - Sarnia General",
        "type": "hospital",
        "address": "89 Norman St",
        "city": "Sarnia",
        "latitude": 42.9936,
        "longitude": -82.3988,
        "phone": "519-464-4400",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "cardiac", "orthopedic", "general"],
    },

    # ── British Columbia — Vancouver Metro ────────────────────────────────────
    {
        "name": "Vancouver General Hospital",
        "type": "hospital",
        "address": "899 W 12th Ave",
        "city": "Vancouver",
        "latitude": 49.2624,
        "longitude": -123.1241,
        "phone": "604-875-4111",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "trauma", "cardiac", "transplant", "neuroscience"],
    },
    {
        "name": "St. Paul's Hospital",
        "type": "hospital",
        "address": "1081 Burrard St",
        "city": "Vancouver",
        "latitude": 49.2807,
        "longitude": -123.1263,
        "phone": "604-682-2344",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "cardiac", "addiction", "HIV", "respiratory"],
    },
    {
        "name": "BC Children's Hospital",
        "type": "hospital",
        "address": "4480 Oak St",
        "city": "Vancouver",
        "latitude": 49.2417,
        "longitude": -123.1386,
        "phone": "604-875-2345",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["pediatric", "emergency", "oncology", "cardiac"],
    },
    {
        "name": "Lions Gate Hospital",
        "type": "hospital",
        "address": "231 E 15th St",
        "city": "North Vancouver",
        "latitude": 49.3204,
        "longitude": -123.0791,
        "phone": "604-988-3131",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "cardiac", "orthopedic", "general"],
    },
    {
        "name": "Surrey Memorial Hospital",
        "type": "hospital",
        "address": "13750 96th Ave",
        "city": "Surrey",
        "latitude": 49.1760,
        "longitude": -122.8458,
        "phone": "604-581-2211",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "trauma", "cardiac", "oncology"],
    },
    {
        "name": "Burnaby Hospital",
        "type": "hospital",
        "address": "3935 Kincaid St",
        "city": "Burnaby",
        "latitude": 49.2495,
        "longitude": -122.9619,
        "phone": "604-434-4211",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "orthopedic", "general"],
    },
    {
        "name": "Royal Columbian Hospital",
        "type": "hospital",
        "address": "330 E Columbia St",
        "city": "New Westminster",
        "latitude": 49.2027,
        "longitude": -122.9073,
        "phone": "604-520-4253",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "trauma", "cardiac", "neuroscience"],
    },
    {
        "name": "Vancouver Urgent Care Centre - Downtown",
        "type": "urgent_care",
        "address": "1067 Burrard St",
        "city": "Vancouver",
        "latitude": 49.2789,
        "longitude": -123.1249,
        "phone": "604-681-5338",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "22:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    {
        "name": "Carepoint Medical - Broadway",
        "type": "clinic",
        "address": "1623 Commercial Dr",
        "city": "Vancouver",
        "latitude": 49.2726,
        "longitude": -123.0697,
        "phone": "604-709-5500",
        "is_open_24_7": False,
        "opening_time": "09:00",
        "closing_time": "20:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general", "family"],
    },

    # ── British Columbia — Kelowna / Victoria ─────────────────────────────────
    {
        "name": "Kelowna General Hospital",
        "type": "hospital",
        "address": "2268 Pandosy St",
        "city": "Kelowna",
        "latitude": 49.8858,
        "longitude": -119.4948,
        "phone": "250-862-4000",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "cardiac", "cancer", "orthopedic"],
    },
    {
        "name": "Royal Jubilee Hospital",
        "type": "hospital",
        "address": "1952 Bay St",
        "city": "Victoria",
        "latitude": 48.4284,
        "longitude": -123.3365,
        "phone": "250-370-8000",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "cardiac", "cancer", "orthopedic"],
    },
    {
        "name": "Victoria General Hospital",
        "type": "hospital",
        "address": "1 Hospital Way",
        "city": "Victoria",
        "latitude": 48.4450,
        "longitude": -123.4102,
        "phone": "250-727-4212",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "trauma", "pediatric", "orthopedic"],
    },
    {
        "name": "Victoria Urgent Care - Oak Bay",
        "type": "urgent_care",
        "address": "1595 McKenzie Ave",
        "city": "Victoria",
        "latitude": 48.4498,
        "longitude": -123.3601,
        "phone": "250-595-1411",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "22:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },

    # ── Alberta — Calgary ─────────────────────────────────────────────────────
    {
        "name": "Foothills Medical Centre",
        "type": "hospital",
        "address": "1403 29 St NW",
        "city": "Calgary",
        "latitude": 51.0680,
        "longitude": -114.1338,
        "phone": "403-944-1110",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "trauma", "cardiac", "neuroscience", "transplant"],
    },
    {
        "name": "Alberta Children's Hospital",
        "type": "hospital",
        "address": "2888 Shaganappi Trail NW",
        "city": "Calgary",
        "latitude": 51.0777,
        "longitude": -114.1716,
        "phone": "403-955-7211",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["pediatric", "emergency", "oncology", "cardiac"],
    },
    {
        "name": "Rockyview General Hospital",
        "type": "hospital",
        "address": "7007 14 St SW",
        "city": "Calgary",
        "latitude": 50.9924,
        "longitude": -114.1349,
        "phone": "403-943-3000",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "cardiac", "orthopedic", "general"],
    },
    {
        "name": "South Health Campus",
        "type": "hospital",
        "address": "4448 Front St SE",
        "city": "Calgary",
        "latitude": 50.8780,
        "longitude": -113.9810,
        "phone": "403-956-1111",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "cardiac", "orthopedic", "women_health"],
    },
    {
        "name": "Calgary Urgent Care - Southcentre",
        "type": "urgent_care",
        "address": "100 Anderson Rd SE",
        "city": "Calgary",
        "latitude": 50.9290,
        "longitude": -114.0706,
        "phone": "403-943-9300",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "22:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    {
        "name": "Crowfoot Urgent Care",
        "type": "urgent_care",
        "address": "600 Crowfoot Crescent NW",
        "city": "Calgary",
        "latitude": 51.1042,
        "longitude": -114.2041,
        "phone": "403-241-5044",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "22:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    {
        "name": "Red Deer Regional Hospital Centre",
        "type": "hospital",
        "address": "3942 50A Ave",
        "city": "Red Deer",
        "latitude": 52.2597,
        "longitude": -113.7909,
        "phone": "403-343-4422",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "cardiac", "orthopedic", "general"],
    },

    # ── Alberta — Edmonton ────────────────────────────────────────────────────
    {
        "name": "University of Alberta Hospital",
        "type": "hospital",
        "address": "8440 112 St NW",
        "city": "Edmonton",
        "latitude": 53.5227,
        "longitude": -113.5272,
        "phone": "780-407-8822",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "trauma", "cardiac", "transplant", "neuroscience"],
    },
    {
        "name": "Royal Alexandra Hospital",
        "type": "hospital",
        "address": "10240 Kingsway Ave",
        "city": "Edmonton",
        "latitude": 53.5560,
        "longitude": -113.5162,
        "phone": "780-735-4111",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "trauma", "women_health", "neonatal"],
    },
    {
        "name": "Grey Nuns Community Hospital",
        "type": "hospital",
        "address": "1100 Youville Dr W",
        "city": "Edmonton",
        "latitude": 53.4740,
        "longitude": -113.4297,
        "phone": "780-735-7000",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "cardiac", "orthopedic", "general"],
    },
    {
        "name": "Edmonton Urgent Care Clinic - Westend",
        "type": "urgent_care",
        "address": "178 St & Stony Plain Rd",
        "city": "Edmonton",
        "latitude": 53.5381,
        "longitude": -113.6262,
        "phone": "780-413-6777",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "22:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },
    {
        "name": "Misericordia Community Hospital",
        "type": "hospital",
        "address": "16940 87 Ave NW",
        "city": "Edmonton",
        "latitude": 53.5471,
        "longitude": -113.5739,
        "phone": "780-735-2000",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "ophthalmology", "orthopedic", "general"],
    },

    # ── Manitoba — Winnipeg ───────────────────────────────────────────────────
    {
        "name": "Health Sciences Centre Winnipeg",
        "type": "hospital",
        "address": "820 Sherbrook St",
        "city": "Winnipeg",
        "latitude": 49.9023,
        "longitude": -97.2211,
        "phone": "204-787-3661",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "trauma", "cardiac", "transplant", "pediatric"],
    },
    {
        "name": "St. Boniface Hospital",
        "type": "hospital",
        "address": "409 Tache Ave",
        "city": "Winnipeg",
        "latitude": 49.8829,
        "longitude": -97.1229,
        "phone": "204-233-8563",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "cardiac", "cancer", "orthopedic"],
    },
    {
        "name": "Grace Hospital Winnipeg",
        "type": "hospital",
        "address": "300 Booth Dr",
        "city": "Winnipeg",
        "latitude": 49.8945,
        "longitude": -97.2405,
        "phone": "204-837-0111",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "cardiac", "general", "seniors"],
    },
    {
        "name": "Winnipeg Urgent Care Centre - McPhillips",
        "type": "urgent_care",
        "address": "1800 McPhillips St",
        "city": "Winnipeg",
        "latitude": 49.9352,
        "longitude": -97.1846,
        "phone": "204-632-3900",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "22:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },

    # ── Saskatchewan ──────────────────────────────────────────────────────────
    {
        "name": "Royal University Hospital",
        "type": "hospital",
        "address": "103 Hospital Dr",
        "city": "Saskatoon",
        "latitude": 52.1351,
        "longitude": -106.6530,
        "phone": "306-655-1000",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "trauma", "cardiac", "transplant", "neuroscience"],
    },
    {
        "name": "St. Paul's Hospital Saskatoon",
        "type": "hospital",
        "address": "1702 20th St W",
        "city": "Saskatoon",
        "latitude": 52.1292,
        "longitude": -106.6680,
        "phone": "306-655-5000",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "cardiac", "orthopedic", "general"],
    },
    {
        "name": "Regina General Hospital",
        "type": "hospital",
        "address": "1440 14th Ave",
        "city": "Regina",
        "latitude": 50.4515,
        "longitude": -104.6189,
        "phone": "306-337-4411",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "cardiac", "cancer", "orthopedic"],
    },
    {
        "name": "Pasqua Hospital Regina",
        "type": "hospital",
        "address": "4101 Dewdney Ave",
        "city": "Regina",
        "latitude": 50.4389,
        "longitude": -104.6712,
        "phone": "306-766-2222",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "cardiac", "general", "pediatric"],
    },

    # ── Quebec — Montreal ─────────────────────────────────────────────────────
    {
        "name": "Montreal General Hospital (MUHC)",
        "type": "hospital",
        "address": "1650 Cedar Ave",
        "city": "Montreal",
        "latitude": 45.4967,
        "longitude": -73.5876,
        "phone": "514-934-1934",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "trauma", "cardiac", "transplant", "neuroscience"],
    },
    {
        "name": "Jewish General Hospital Montreal",
        "type": "hospital",
        "address": "3755 Cote-Sainte-Catherine Rd",
        "city": "Montreal",
        "latitude": 45.4959,
        "longitude": -73.6369,
        "phone": "514-340-8222",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "cardiac", "oncology", "orthopedic"],
    },
    {
        "name": "Hopital Sacre-Coeur de Montreal",
        "type": "hospital",
        "address": "5400 Gouin Blvd W",
        "city": "Montreal",
        "latitude": 45.5334,
        "longitude": -73.7087,
        "phone": "514-338-2222",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "trauma", "cardiac", "pulmonology"],
    },
    {
        "name": "Hopital Maisonneuve-Rosemont",
        "type": "hospital",
        "address": "5415 Assomption Blvd",
        "city": "Montreal",
        "latitude": 45.5544,
        "longitude": -73.5618,
        "phone": "514-252-3400",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "ophthalmology", "hematology", "oncology"],
    },
    {
        "name": "Montreal Children's Hospital (MUHC)",
        "type": "hospital",
        "address": "1001 Decarie Blvd",
        "city": "Montreal",
        "latitude": 45.4960,
        "longitude": -73.5794,
        "phone": "514-412-4400",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["pediatric", "emergency", "oncology", "cardiac"],
    },
    {
        "name": "Cite-de-la-Sante Hospital Laval",
        "type": "hospital",
        "address": "1755 Rene-Laennec Blvd",
        "city": "Laval",
        "latitude": 45.5621,
        "longitude": -73.7456,
        "phone": "450-668-1010",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "cardiac", "oncology", "general"],
    },
    {
        "name": "GMF Urgence Sante - Montreal",
        "type": "urgent_care",
        "address": "1170 Peel St",
        "city": "Montreal",
        "latitude": 45.4982,
        "longitude": -73.5718,
        "phone": "514-866-7000",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "21:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general", "family"],
    },

    # ── Quebec — Quebec City ───────────────────────────────────────────────────
    {
        "name": "CHUL - Centre Hospitalier Universite Laval",
        "type": "hospital",
        "address": "2705 Blvd Laurier",
        "city": "Quebec City",
        "latitude": 46.7783,
        "longitude": -71.2837,
        "phone": "418-654-2282",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "cardiac", "transplant", "neuroscience"],
    },
    {
        "name": "Hopital de l'Enfant-Jesus",
        "type": "hospital",
        "address": "1401 18e Rue",
        "city": "Quebec City",
        "latitude": 46.8169,
        "longitude": -71.2368,
        "phone": "418-649-5555",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "trauma", "orthopedic", "general"],
    },

    # ── Nova Scotia — Halifax ─────────────────────────────────────────────────
    {
        "name": "QEII Health Sciences Centre - Halifax Infirmary",
        "type": "hospital",
        "address": "1796 Summer St",
        "city": "Halifax",
        "latitude": 44.6395,
        "longitude": -63.5813,
        "phone": "902-473-2700",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "trauma", "cardiac", "transplant", "cancer"],
    },
    {
        "name": "IWK Health Centre",
        "type": "hospital",
        "address": "5980 University Ave",
        "city": "Halifax",
        "latitude": 44.6363,
        "longitude": -63.5899,
        "phone": "902-470-8888",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["pediatric", "women_health", "neonatal", "emergency"],
    },
    {
        "name": "Halifax Urgent Care",
        "type": "urgent_care",
        "address": "1350 Bedford Hwy",
        "city": "Halifax",
        "latitude": 44.6912,
        "longitude": -63.6427,
        "phone": "902-457-8600",
        "is_open_24_7": False,
        "opening_time": "08:00",
        "closing_time": "21:00",
        "accepts_ambulance": False,
        "has_emergency_department": False,
        "specialties": ["general"],
    },

    # ── New Brunswick — Fredericton / Moncton ─────────────────────────────────
    {
        "name": "Dr. Everett Chalmers Regional Hospital",
        "type": "hospital",
        "address": "700 Priestman St",
        "city": "Fredericton",
        "latitude": 45.9527,
        "longitude": -66.6476,
        "phone": "506-452-5400",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "cardiac", "cancer", "orthopedic"],
    },
    {
        "name": "The Moncton Hospital",
        "type": "hospital",
        "address": "135 MacBeath Ave",
        "city": "Moncton",
        "latitude": 46.1060,
        "longitude": -64.7966,
        "phone": "506-857-5111",
        "is_open_24_7": True,
        "opening_time": None,
        "closing_time": None,
        "accepts_ambulance": True,
        "has_emergency_department": True,
        "specialties": ["emergency", "cardiac", "cancer", "trauma"],
    },
]

LIVE_STATUS_PRESETS = {
    "hospital": {"wait_range": (30, 180), "capacity_range": (0.5, 0.95)},
    "er":       {"wait_range": (45, 240), "capacity_range": (0.6, 1.0)},
    "urgent_care": {"wait_range": (10, 60),  "capacity_range": (0.2, 0.75)},
    "clinic":   {"wait_range": (5, 40),   "capacity_range": (0.1, 0.6)},
    "pharmacy": {"wait_range": (0, 10),   "capacity_range": (0.0, 0.3)},
}


def seed(reset: bool = False):
    db = SessionLocal()
    try:
        if db.query(models.CareLocation).count() > 0:
            if not reset:
                print("Database already seeded - skipping. Use --reset to wipe and reseed.")
                return
            # Wipe in order (FKs: references to care_locations first)
            db.query(wait_times.models.WaitTimeScenario).delete()
            db.query(wait_times.models.WaitTimeSourceRecord).delete()
            db.query(wait_times.models.WaitTimeSnapshot).delete()
            db.query(models.RoutingRecommendation).delete()
            db.query(models.Handoff).delete()
            db.query(models.Alert).delete()
            db.query(models.VisitOutcome).delete()
            db.query(models.LiveStatus).delete()
            db.query(models.LocationSpecialty).delete()
            db.query(models.CareLocation).delete()
            db.commit()
            db = SessionLocal()

        seeded_locations = []
        for raw_loc_data in CARE_LOCATIONS:
            loc_data = dict(raw_loc_data)
            specialties = loc_data.pop("specialties", [])

            location = models.CareLocation(**loc_data)
            db.add(location)
            db.flush()  # get the auto-generated id
            seeded_locations.append(location)

            for specialty in specialties:
                db.add(models.LocationSpecialty(
                    care_location_id=location.id,
                    specialty_name=specialty,
                ))

            preset = LIVE_STATUS_PRESETS.get(location.type, LIVE_STATUS_PRESETS["clinic"])
            current_wait = random.randint(*preset["wait_range"])
            capacity = round(random.uniform(*preset["capacity_range"]), 2)

            db.add(models.LiveStatus(
                care_location_id=location.id,
                current_wait_mins=current_wait,
                predicted_wait_on_arrival_mins=max(0, current_wait + random.randint(-10, 20)),
                capacity_score=capacity,
                queue_length=int(capacity * random.randint(5, 30)),
                staffing_level=random.choice(["low", "normal", "normal", "high"]),
                ambulance_load=random.randint(0, 3) if location.accepts_ambulance else 0,
                last_updated_at=datetime.now(timezone.utc),
            ))

        db.commit()
        refresh_wait_times_for_locations(db, seeded_locations, force=True)
        db.commit()
        print(f"Seeded {len(CARE_LOCATIONS)} care locations with live status.")
    except Exception as exc:
        db.rollback()
        raise exc
    finally:
        db.close()


if __name__ == "__main__":
    seed(reset="--reset" in sys.argv)
